### ISSUE TITLE
update the site domain

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/phenovista-digital-storefront#17]
### ref
- https://github.com/scientist-softserv/webstore/issues/322

# Acceptance Criteria
- [ ] the site is deployed at the domain below

# Story
from the client:
> Subdomain will be [store.phenovista.com](http://store.phenovista.com/)

**Comment by alishaevn** [comment]
blocked by:
- https://github.com/scientist-softserv/webstore/issues/322

**Comment by orangewolf** [comment]
put up an ingress so it can go live when they are ready

**Comment by alishaevn** [comment]
https://assaydepot.slack.com/archives/C03FZDALABG/p1701473464029599?thread_ts=1701463346.578699&cid=C03FZDALABG

**Comment by alishaevn** [comment]
crystal sent the following email to the phenovista team on Dec. 1, 2023 in the "Re: Follow Up on Assets for Digital Storefront" thread.

> We have the site deployed to the permanent servers and an ingress is set up for the domain switch.  You can view the site currently at : https://phenovista.softserv.cloud/
>
> When you are ready, you can switch the DNS by creating a cname that points [store.phenovista.com](http://store.phenovista.com/) to phenovista.softserv.cloud. This will cause that domain to go “live”. Once you do so there will be an ssl issue for 5ish minutes (maybe more depending on the back off since it tries to get the ssl over and over until it works)
