### ISSUE TITLE
fix the deploy

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/phenovista-digital-storefront#31]
# Summary
I've been unable to deploy phenovista this week. we will need to deploy it by December 20, 2023.

# Acceptance Criteria
- [ ] we are able to deploy to phenovista staging and production again

# Screenshots / Video
``` bash
Error: UPGRADE FAILED: release phenovista-digital-storefront-staging failed, and has been rolled back due to atomic being set: timed out waiting for the condition
Error: Process completed with exit code 1.
```

# Story
all this week the deploy to staging has been failing. normally in about 15-18 seconds. the error above led me to [this article](https://playbook-staging.notch8.com/en/devops/standard-stacks/deployment-troubleshooting), so I viewed the secrets in rancher. I tried deleting the most recent helm release and redeploying. that didn't work so I deleted two releases and redeployed. over the past few days I've tried variations of the above. even starting new deploys instead of redeploying a failed deploy. 

this morning I decided to delete the 5 releases all the way back to december 6, which was the last [successful deploy](https://github.com/scientist-softserv/phenovista-digital-storefront/actions/runs/7118893139/job/19382809731). (from a branch to production) I kicked off a [new deploy](https://github.com/scientist-softserv/phenovista-digital-storefront/actions/runs/7211344047/job/19646567013) and this time it got all the way to 17 minutes before failing. 

unsure if it's related, but every time I do a deploy, two helm releases are created. not at the exact same time, but within a few minutes of each other typically. as seen below

<img width="1067" alt="image" src="https://github.com/scientist-softserv/phenovista-digital-storefront/assets/29032869/edcc485b-d9aa-46d9-8e63-b2ef8a20b28f">

**Comment by ShanaLMoore** [comment]
That error you captured isn't the true error. It'd be easier to show you how to fetch the real error.

**Comment by ShanaLMoore** [comment]
Jk, April beat me to it in slack! https://assaydepot.slack.com/archives/C0313NK4SMS/p1702577225570219?thread_ts=1702576735.323009&cid=C0313NK4SMS
