### ISSUE TITLE
Authorization Flow Issues

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/phenovista-digital-storefront#46]
# story
occasionally, when logging in to the phenovista marketplace from their digital storefront, the user is redirected to the next auth sign in page instead of routing them directly to the marketplace. the behavior in the screenshot below is what happens when the provider's id isn't passed to the `signIn` method. we are passing it however, so debugging needs to be done to see why we aren't bypassing the nextauth sign in page.

Digital storefront user journey: 
https://docs.google.com/document/d/1nNvUxzInahqMrVZWGCyVnskmJvMo4c1k5oqKwwSYvIY/edit

# screenshots
![Image](https://github.com/scientist-softserv/webstore/assets/11359350/6d762917-479b-40ce-a96a-d263e4b6d7d3)

# resources
- https://next-auth.js.org/getting-started/client#signin

# notes
- normally, this page could show multiple sign in methods (i.e. - sign in with google, facebook etc) but in our case, we should only have the option to sign in with the provider. 
- this page should never show - because we are passing the provider ID in our sign in method. we don't want to see it because we only have one sign in method.
- this page should always be bypassed but sometimes it gets sent there - but its not a consistent issue.
- https://github.com/scientist-softserv/webstore/blob/main/pages/_app.js#L47 - where we are passing the provider name.

**Comment by alishaevn** [comment]
potential clues:
- https://github.com/nextauthjs/next-auth/discussions/1299#discussioncomment-362054
- https://stackoverflow.com/a/77742170/8079848

**Comment by alishaevn** [comment]
crystal suggested in stand up that this issue _might_ be able to be fixed from the devops side. started a [thread](https://assaydepot.slack.com/archives/C0313NK4SMS/p1707153816402189) for possible suggestions.
