### ISSUE TITLE
Change Truncation to display all services

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/phenovista-digital-storefront#71]
# Story
The tructation on the Browse page cuts the text strangely and adds a blank.  This makes it hard to read.  

# Acceptance Criteria

- [ ] Cell Painting and Custom Assay Services no longer show a 'read more' 

# Screenshots / Video

<img width="1161" alt="Screenshot 2024-05-07 at 3 40 43 PM" src="https://github.com/scientist-softserv/phenovista-digital-storefront/assets/11359350/fc2d049c-8bd1-424b-b864-fdce470f7a38">

# Testing Instructions and Sample Files

- Go to the Browse page
- look at the cell painting and custom assay services

# Notes

**Comment by labradford** [comment]
added the contribute back label because this added a feature to webstore component library

**Comment by alishaevn** [comment]
for some reason the "show more/less" toggle is still present after updating the wcl version to include the latest changes.

![Image](https://github.com/scientist-softserv/phenovista-digital-storefront/assets/29032869/c74d33b5-d010-44fa-8ae8-b402eae470ff)

**Comment by alishaevn** [comment]
this was resolved last week by re-releasing the wcl.
