### ISSUE TITLE
Remove intercom and privacy policy opt in from sign in, sign up page

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/phenovista-digital-storefront#74]
# Story
Intercom access and the privacy policy is not the same for webstore as the rest of the app.  Remove intercom and the privacy policy opt out banner from the unbranded sign in/sign up pages.  The privacy policy from phenovista should be linked on the bottom of the sign in/sign up page.  (https://store.phenovista.com/legal-notices/privacy-policy)

# Acceptance Criteria

- [ ] When a user goes to sign in/sign up for phenovista webstore they should not have a pricacy policy opt in, or see intercom.  
- [ ] There should be a link to the phenovista priacy policy.  

# Screenshots / Video

# Testing Instructions and Sample Files

-

# Notes

**Comment by labradford** [comment]
This work will probably be in Rx app starting with the `app/views/layouts/unbranded.haml`, removing the footer (cookie notice and footer_js)
