### ISSUE TITLE
Sign up Flow should be simplified and non scientist branded

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/phenovista-digital-storefront#75]
# Story
The sign up flow for webstores should not have scientist.com branding or take you to the scientist.com storefront for phenovista.  

# Acceptance Criteria

- [ ] I am able to sign up and submit any information I need without seeing anything scientist.com branding. 
- [ ] The amount of info I have to add is as limited as possible.  

# Screenshots / Video

# Testing Instructions and Sample Files

-

# Notes

as of right now, clicking “sign in” from the DS, I’m redirected to the phenovista branded login page at https://phenovista.assayexpress.com/login.
I created a new email/pw user with a non scientist domain and was taken to a “confirm my account” page.
I pressed the “confirm my account” link from my email, and was redirected to a new tab at https://phenovista.assayexpress.com/onboarding/organization.  we shouldn’t be taken here anymore, but this is the process that zak was [working on last week](https://assaydepot.slack.com/archives/C03FZDALABG/p1713808761050529). I’m unsure what the status of the work is at the moment.
I created a fake org, signed the marketplace agreement and went through the rest of the typical onboarding steps. then I was left on the storefront dashboard. this makes sense because the confirmation link in my email opened up a new tab. therefore, the new tab has no knowledge of the DS to know anything about a redirect back.
I returned to the original tab that I created my user from, which is now on the “confirm your account” page. pressing “log in” from that page said that I was already logged in, but still took me to the “favorites” tab of the onboarding process. I skipped it and was taken to the storefront dashboard again.
I logged out of https://phenovista.assayexpress.com/, and went back to https://store.phenovista.com/. starting the “sign in process all over, I was again taken to the phenovista branded log in page. logging in with my already confirmed email/ps user, properly redirected me back to the DS without seeing any of the storefront.
so the login process for existing users should work as expected. the new user process still has some work to be done.

**Comment by alishaevn** [comment]
potentially blocked by https://github.com/assaydepot/rx/issues/24075.

**Comment by alishaevn** [comment]
related: https://github.com/assaydepot/rx/issues/25898

**Comment by alishaevn** [comment]
created a new user on main to test this locally and figure out the issues:
1. in the confirmation email the "from" says "support@scientist.com"
2. when the user clicks the email they are redirected to the onboarding flow of the phenovista site.
3. opening a new tab, going back to localhost:3001 (local phenovista) and pressing the sign in button took me to the unbranded phenovista.scientist.dev login page. however, logging in still took me to the marketplace dashboard instead of redirecting me.

created https://github.com/assaydepot/rx/issues/26333 to track this work against rx since that's where the work will be done.

**Comment by alishaevn** [comment]
completed on https://github.com/assaydepot/rx/issues/26333
