### ISSUE TITLE
New Request Changes

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/phenovista-digital-storefront#76]
# Story
This ticket has not been filled out yet, as we need to see if any changes are required after changes were made by professional services.  Page is currently erroring. 

# Acceptance Criteria

- [ ]

# Screenshots / Video

<img width="979" alt="Screenshot 2024-05-07 at 4 47 44 PM" src="https://github.com/scientist-softserv/phenovista-digital-storefront/assets/11359350/0cfca66a-b48d-4afd-bdda-daa569c9cf13">

# Testing Instructions and Sample Files

-

# Notes

**Comment by labradford** [comment]
waiting for fixes to deploy so we can verify if this is fixed

**Comment by alishaevn** [comment]
all fixes thus far have been updated in local dev. there are still issues on the "new request" page:

![Image](https://github.com/scientist-softserv/phenovista-digital-storefront/assets/29032869/6dd7f37d-e731-4a9e-a4b0-cce0b2ed0638)

**Comment by alishaevn** [comment]
this is working on production.

ref: https://assaydepot.slack.com/archives/C03FZDALABG/p1716488190737599?thread_ts=1714579221.538069&cid=C03FZDALABG
